version: '2'

services:
  postgresql:
    container_name: treasyapi_db
    image: nogsantos/postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - PG_PASSWORD=123456
      - DB_NAME=treasy
    volumes:
      - ./postgres/scripts:/scripts:rw
      - ./postgres/data:/var/lib/postgresql:rw
